In [18]:
import numpy as np  


In [19]:
array=np.array([1,2,3,4,5,6,7,8,9])
print(array)
array_2=array+50
print(array_2)

[1 2 3 4 5 6 7 8 9]
[51 52 53 54 55 56 57 58 59]


In [9]:
new_arr=np.insert(array,3,10)
# print(new_arr)
new_arr=np.insert(new_arr,6,10)
# print(new_arr)
new_arr=np.insert(new_arr,8,10)
print(new_arr)

[ 1  2  3 10  4  5 10  6 10  7  8  9]


In [11]:
arr=np.array([10,20,30,40,50,60,70,80,90])
print(arr)

index_add = [3, 6, 8 ,2]
value_add=200,
for index in index_add:
    arr=np.insert(arr,index,value_add)
print(arr)



[10 20 30 40 50 60 70 80 90]
[ 10  20 200  30 200  40  50 200  60 200  70  80  90]


In [13]:
print(arr.shape)
arr.size

(13,)


13

In [ ]:
TASK1

In [5]:
import pandas as pd

In [7]:
import pandas as pd
data = { 
    'A': [1, 2, 3, 4, 5, 6], 
    'B': [7, 8, 9, 10, 11, 12], 
    'C': [13, 14, 15, 16, 17, 18] }
    

In [9]:
frame=pd.DataFrame(data)
frame

A   B   C
0  1   7  13
1  2   8  14
2  3   9  15
3  4  10  16
4  5  11  17
5  6  12  18

In [13]:
frame.head(3)


A  B   C
0  1  7  13
1  2  8  14
2  3  9  15

In [15]:
frame.tail(3)

A   B   C
3  4  10  16
4  5  11  17
5  6  12  18