In [ ]:
#Random Namber

In [3]:
import numpy as np


In [6]:
arr1 = np.random.rand(5)
arr1

array([0.02253004, 0.17182915, 0.75671992, 0.30832339, 0.81057662])

In [7]:
arr2 = np.random.rand(2 ,5)
arr2

array([[0.12268916, 0.31202779, 0.62834444, 0.53868898, 0.88458308],
       [0.42786756, 0.326529  , 0.30957884, 0.00177975, 0.47224602]])

In [8]:
arr3 = np.random.randn(4)
arr3

array([ 0.05444241, -0.84052123, -1.73285533, -2.55272723])

In [10]:
arr4 = np.random.rand(3 ,6)
arr4

array([[0.0251122 , 0.5147092 , 0.65369492, 0.65273086, 0.19895004,
        0.7496415 ],
       [0.34168296, 0.87726328, 0.76284083, 0.1885414 , 0.98412769,
        0.86578315],
       [0.9469871 , 0.71369645, 0.07707171, 0.85753379, 0.55439547,
        0.76980155]])

In [18]:
arr5 = np.random.ranf(5)
arr5

array([0.65553965, 0.98757264, 0.36042891, 0.35481858, 0.62492881])

In [21]:
arr6 = np.random.randint(6 , 10 ,8)
arr6

array([7, 7, 6, 7, 9, 7, 9, 8])

In [ ]:
#types of Numpy 

In [40]:
arr11 = np.array([20 ,30 ,40 ,30 ,10 ,60 ])
print(arr11 , arr11.dtype)

[20 30 40 30 10 60] int32


In [46]:
arr22 = np.array([10 , 20 ,30 ,40 ,50 ,60] ,dtype = np.int8) 
print("Data Type :" , arr22.dtype)
print(arr22 )
print(arr22.dtype)

Data Type : int8
[10 20 30 40 50 60]
int8


In [49]:
arr33 = np.array([2 , 3, 5, 6 ,7])
new = np.float32(arr33) 
new1 = np.int_(new)
print("Data type:" , arr33.dtype)
print("Data type:" , new.dtype)
print("Data type :" , new1.dtype)
print(arr33)
print(new)
print(new1)

Data type: int32
Data type: float32
Data type : int32
[2 3 5 6 7]
[2. 3. 5. 6. 7.]
[2 3 5 6 7]


In [51]:
import numpy as np

# Define two matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Method 1: Using numpy.dot
result1 = np.dot(matrix1, matrix2)

# Method 2: Using the @ operator
result2 = matrix1 @ matrix2

print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nResult using np.dot:")
print(result1)
#print("\nResult using @ operator:")
#print(result2)


Matrix 1:
[[1 2]
 [3 4]]

Matrix 2:
[[5 6]
 [7 8]]

Result using np.dot:
[[19 22]
 [43 50]]


In [66]:
ar = np.array([8, 2, 3, 4, 5])

print("min:", np.min(ar), "index of min:", ar.argmin())
print("max:", np.max(ar), "index of max:", ar.argmax())
print("sqrt :", np.sqrt(ar)) 


min: 2 index of min: 1
max: 8 index of max: 0
sqrt : [2.82842712 1.41421356 1.73205081 2.         2.23606798]


In [69]:
ar2 = np.array([ 0, 1 ,2 ,3 , 4, 5, 6])
print( np.sin(ar2))
print(np.cos(ar2))
print(np.cumsum(ar2))
      

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155 ]
[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029]
[ 0  1  3  6 10 15 21]


In [70]:
ar3 = np.array([1,2,3]) 
print(np.tan(ar3))

[ 1.55740772 -2.18503986 -0.14254654]


In [71]:
ar4 = np.array([0])
print(np.sin(ar4))

[0.]


In [72]:
print(np.cos(ar4))

[1.]


In [80]:
arrr = np.array([2, 3,4 ,5, 6,7, 8])
arrr1 = np.array([4, 5, 6, 7, 6, 7, 7])
x = arrr+arrr1
x

array([ 6,  8, 10, 12, 12, 14, 15])

In [82]:
x+2


array([ 8, 10, 12, 14, 14, 16, 17])

In [109]:
arr5 = np.array([2 ,3 ,4 ,5, 6, 7, 7, 6,5 ,3 ,4 ,4])
arr5.shape

(12,)

In [110]:
arr5.ndim

1

In [121]:
a =arr5.reshape(2,3 , 2)
a

array([[[2, 3],
        [4, 5],
        [6, 7]],

       [[7, 6],
        [5, 3],
        [4, 4]]])

In [130]:
arr6 = np.array([[[2,3,4,5,7,8]] ,[[3 ,4 ,5 ,6, 7, 8]], [[4,5,6, 7, 7, 8]]])
arr6

array([[[2, 3, 4, 5, 7, 8]],

       [[3, 4, 5, 6, 7, 8]],

       [[4, 5, 6, 7, 7, 8]]])

In [131]:
arr6.shape

(3, 1, 6)

In [132]:
t = arr6.reshape(-1)
t

array([2, 3, 4, 5, 7, 8, 3, 4, 5, 6, 7, 8, 4, 5, 6, 7, 7, 8])

In [133]:
arr6[1]

array([[3, 4, 5, 6, 7, 8]])

In [134]:
t[1]

3