In [1]:
import numpy as np

In [23]:
# This is to show that simply adding a number to the elements of a simple array will not work
arr_1 = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
arr_0 = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
# arr_1+arr_0 
# type(arr_1)
# arr_1 += 1
# for i in range(len(arr_1)): 
#     print(arr_1[i])

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15]

In [19]:
# But you can do it in a numpy array
arr_2 = np.array([1,2,3,4,5,6])
print (type(arr_2))
print(arr_2.shape)

<class 'numpy.ndarray'>
(6,)


In [18]:
# adding +1 to all elements of a numpy array
arr_3 = arr_2 + 1
# arr_2 += 2
print(arr_3)
# arr_2 += 1
# arr_2

[ 5  6  7  8  9 10]


In [20]:
# Adding elements to numpy array
arr_3 + arr_2

array([ 6,  8, 10, 12, 14, 16])

In [22]:
a=10
b=20
a+b


30

In [24]:
# Multiplying elements
arr_2 * arr_3

array([ 5, 12, 21, 32, 45, 60])

In [29]:
# Element at specific index number, in this instance it's "0". 
# we always count positions from zero in arrays.
arr_2 [0], arr_2[1]

(1, 2)

In [39]:
# To select a range. in this case, it's index position 1 till the end.
arr_2 [:-3]  # [start, end]

array([1, 2, 3])

In [44]:
# You can have a multidimensional array with different data types.
a=np.array(
    [
        [1, 2, "a"],[1.5,2.5,"b"]
    ]
)
a
# np.array([[1,2,3],["a","b","c"]])

array([['1', '2', 'a'],
       ['1.5', '2.5', 'b']], dtype='<U32')

In [46]:
        # Appending an element
arr = np.array([1, 2, 3])
print("Original array :", arr)
new_arr = np.append(arr, 4)
print("New array :", new_arr)

Original array : [1 2 3]
New array : [1 2 3 4]


In [47]:
# Adding an element at index 1
new_arr = np.insert(arr, 1, 5)
print("Original array :", arr)
print("New array :", new_arr)

Original array : [1 2 3]
New array : [1 5 2 3]
