In [3]:
import numpy as np

m_1 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
m_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**----------------------------------------------------------------------------------------------------**

**Note below that making a new variable and manipulating it also changes the original variable**

In [4]:
m_2 = m_1
m_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
            # Replaces a specific value
m_2[1,2] = 600
m_2

array([[  1,   2,   3],
       [  4,   5, 600],
       [  7,   8,   9]])

In [6]:
m_1

array([[  1,   2,   3],
       [  4,   5, 600],
       [  7,   8,   9]])

**Note that both the outputs of m_1 and M_2 are exactly the same even though we just changed m_2**

**---------------------------------------------------------------------------------------------------**

**But if we use "np.copy" function, we don't get the same problem**

In [7]:
m3= np.copy(m_1)
m3[1,2] = 900
m3

array([[  1,   2,   3],
       [  4,   5, 900],
       [  7,   8,   9]])

In [8]:
m_1

array([[  1,   2,   3],
       [  4,   5, 600],
       [  7,   8,   9]])

**m_1 and m3 are different**

**-----------------------------------------------------------------------------------------------------------------------**

In [2]:
            # Creates a NumPy array m_4 with values starting from 0 up to (but not including) 100, in steps of 20.
import numpy as np
m_4 = np.arange(0,100,10)
m_4

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

**-----------------------------------------------------------------------------------------------------------------------**

**Creates a NumPy array m_5 of shape (100,) filled with random values drawn from a uniform distribution over the interval**
**[0, 1].**

In [5]:
m_5 = np.random.rand(100,3)
m_5

array([[0.37548915, 0.49067492, 0.45900257],
       [0.66613325, 0.16167498, 0.27511384],
       [0.07860978, 0.36390769, 0.9158948 ],
       [0.53884405, 0.28019283, 0.18123757],
       [0.0218917 , 0.10886908, 0.81627409],
       [0.90585487, 0.36704829, 0.71440925],
       [0.40305761, 0.30331427, 0.35440466],
       [0.59138046, 0.68839877, 0.87926199],
       [0.88356889, 0.24850214, 0.59739971],
       [0.923986  , 0.59223096, 0.50338   ],
       [0.84295666, 0.29510873, 0.04330384],
       [0.95314761, 0.93205804, 0.46804146],
       [0.73378445, 0.90581875, 0.18660695],
       [0.15582806, 0.19387598, 0.70558399],
       [0.9184946 , 0.12306984, 0.80080246],
       [0.60301644, 0.92046959, 0.20931187],
       [0.84727955, 0.55881801, 0.55872994],
       [0.95828138, 0.55827698, 0.86376819],
       [0.85911878, 0.41902839, 0.69484486],
       [0.7073535 , 0.52665848, 0.40352412],
       [0.16912192, 0.44319206, 0.47459343],
       [0.80521706, 0.23876717, 0.66836922],
       [0.