In [6]:
import numpy as np

In [2]:
                # Initialize an array
arr_1 = np.array([1,2,3,4], dtype = np.float32)
arr_1

array([1., 2., 3., 4.], dtype=float32)

In [3]:
                # shows the number of bytes occupied by the array
arr_1.nbytes

16

In [9]:
# Creates a NumPy array arr_2 with elements of mixed types (integer, float, string) stored as generic Python objects.
arr_2 = np.array([1,2.0,"3"], dtype = object)
arr_2

array([1, 2.0, '3'], dtype=object)

In [10]:
        # Shows how different data types handle mathematical operations performed on them
arr_2 * 3

array([3, 6.0, '333'], dtype=object)

In [11]:
        # Changed the data type of the array.
arr_3 = np.array([1,2,3])
np.asarray(arr_3, dtype = np.float32)

array([1., 2., 3.], dtype=float32)

In [12]:
arr_3

array([1, 2, 3])

In [13]:
        # Changes the data type of an array
arr_4 = np.asarray(arr_3, dtype = np.float32)

In [14]:
arr_4

array([1., 2., 3.], dtype=float32)