In [ ]:
import numpy as np

In [ ]:
arr_1 = np.array([[1,2,3],[4,5,6]])
arr_1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
                # Sum of all elements in the array
np.sum(arr_1)

21

In [ ]:
                # Sum of each row
np.sum(arr_1, axis=1)

array([ 6, 15])

In [ ]:
                # Sum of each column
np.sum(arr_1, axis=0)

array([5, 7, 9])

In [ ]:
                # Product of all elements in the array
arr_1.prod()

720

In [ ]:
                # Product of each column
arr_1.prod(axis=0)

array([ 4, 10, 18])

In [ ]:
                # Product of each rows
arr_1.prod(axis=1)

array([  6, 120])

In [ ]:
                # Minimum value in the array
arr_1.min()

1

In [ ]:
                # Minimum value in each column
arr_1.min(axis=0)

array([1, 2, 3])

In [ ]:
                # Minimum value in each row
arr_1.min(axis=1)

array([1, 4])

In [ ]:
                # Maximum value in the array
arr_1.max()

6

In [ ]:
                # Index of the minimum element
arr_1.argmin()

0

In [ ]:
                # Index of the minimum element in each column
arr_1.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [ ]:
                # Index of the maximum element
arr_1.argmin(axis=1)

array([0, 0], dtype=int64)

In [ ]:
                # Index of the maximum element
arr_1.argmax()

5

In [ ]:
                # Mean of the array
arr_1.mean()

3.5

In [ ]:
                # Mean of each column
arr_1.mean(axis=0)

array([2.5, 3.5, 4.5])

In [ ]:
                # Standard deviation of the array
arr_1.std()

1.707825127659933

In [ ]:
                # Standard deviation of each row
arr_1.std(axis=1)

array([0.81649658, 0.81649658])

In [ ]:
                # Variance of the array
arr_1.var()

2.9166666666666665

In [ ]:
arr_1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
                # Clip the values of the array between 2 and 4
arr_1.clip(2,4)

array([[2, 2, 3],
       [4, 4, 4]])

In [ ]:
                # Round the values
arr_2 = np.array([4.12,5.5,6.666])
arr_2.round()

array([4., 6., 7.])

In [ ]:
                # Round to 2 decimal places
arr_2.round(decimals=2)

array([4.12, 5.5 , 6.67])

In [ ]:
arr_1 = np.array([[5.5,1.1,8.7],
                 [4.5,9.8,0.9]])
arr_1

array([[5.5, 1.1, 8.7],
       [4.5, 9.8, 0.9]])

In [ ]:
                # Sort the array
np.sort(arr_1)

array([[1.1, 5.5, 8.7],
       [0.9, 4.5, 9.8]])