In [1]:
import pandas as pd

In [3]:
data = { 'A': [1, 2, 3, 4, 5, 6], 'B': [7, 8, 9, 10, 11, 12], 'C': [13, 14, 15, 16, 17, 18] }

In [5]:
df=pd.DataFrame(data)
df

A   B   C
0  1   7  13
1  2   8  14
2  3   9  15
3  4  10  16
4  5  11  17
5  6  12  18

In [7]:
df.head(3)

A  B   C
0  1  7  13
1  2  8  14
2  3  9  15

In [9]:
df.tail(3)

A   B   C
3  4  10  16
4  5  11  17
5  6  12  18

In [11]:
import numpy as np

In [13]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
array+50

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

In [17]:
array[0]=50
array[1]=60
array[2]=70
array

array([50, 60, 70,  4,  5,  6,  7,  8,  9, 10])